// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-activity-reporter/entity"
	mock "github.com/stretchr/testify/mock"
)

// Follower is an autogenerated mock type for the Follower type
type Follower struct {
	mock.Mock
}

// Follow provides a mock function with given fields: _a0
func (_m *Follower) Follow(_a0 entity.Publisher) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Publisher) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FollowerNotification provides a mock function with given fields: _a0, _a1
func (_m *Follower) FollowerNotification(_a0 entity.Publisher, _a1 entity.Notification) {
	_m.Called(_a0, _a1)
}

// FollowerNotificationAboutActivity provides a mock function with given fields: _a0
func (_m *Follower) FollowerNotificationAboutActivity(_a0 string) {
	_m.Called(_a0)
}

// IsFollowed provides a mock function with given fields: _a0
func (_m *Follower) IsFollowed(_a0 entity.Publisher) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(entity.Publisher) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LikedPhoto provides a mock function with given fields: _a0
func (_m *Follower) LikedPhoto(_a0 entity.Publisher) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Publisher) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserName provides a mock function with given fields:
func (_m *Follower) UserName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// notifyActivityToAll provides a mock function with given fields: _a0, _a1
func (_m *Follower) notifyActivityToAll(_a0 entity.Publisher, _a1 entity.Notification) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewFollower interface {
	mock.TestingT
	Cleanup(func())
}

// NewFollower creates a new instance of Follower. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFollower(t mockConstructorTestingTNewFollower) *Follower {
	mock := &Follower{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
